<a href="https://colab.research.google.com/github/NataliiaHromyk/HomeWork_Python_DS/blob/main/Hromyk_%22HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8)_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#1
a1 = np.array(np.random.uniform(0,1,10))
a2 = np.array(np.random.rand(10))

print("\nВектор a1: ", a1, "\nРозмір вектора а1: ", a1.shape)
print("\nВектор a2: ", a2, "\nРозмір вектора а2: ", a2.shape)


Вектор a1:  [0.3290024  0.55664714 0.39645255 0.41542865 0.40292155 0.70777862
 0.84770759 0.04956474 0.61232608 0.01935842] 
Розмір вектора а1:  (10,)

Вектор a2:  [0.49630986 0.94253295 0.06299538 0.93684387 0.27474208 0.3729146
 0.55326464 0.40004398 0.68238128 0.57039081] 
Розмір вектора а2:  (10,)


In [22]:
M = np.array([[11,14,17],
              [20,23,26],
              [29,32,35]])

print("Матриця: \n", M, "\nРозмір матриці: ", M.shape)

Матриця: 
 [[11 14 17]
 [20 23 26]
 [29 32 35]] 
Розмір матриці:  (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [5]:
#1
a1_10 = np.round(a1+10,2)
a2_10 = np.round(a2+10,2)

a1_10, a2_10

(array([10.33, 10.56, 10.4 , 10.42, 10.4 , 10.71, 10.85, 10.05, 10.61,
        10.02]),
 array([10.5 , 10.94, 10.06, 10.94, 10.27, 10.37, 10.55, 10.4 , 10.68,
        10.57]))

In [6]:
#2
M*2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [7]:
#3 якщо це квадрат кожного елементу, то даний розв'язок підходить
np.multiply(a1, a1)

array([1.08242576e-01, 3.09856034e-01, 1.57174627e-01, 1.72580960e-01,
       1.62345775e-01, 5.00950578e-01, 7.18608161e-01, 2.45666313e-03,
       3.74943225e-01, 3.74748483e-04])

In [26]:
a2*a2

array([0.24632348, 0.88836836, 0.00396842, 0.87767643, 0.07548321,
       0.1390653 , 0.30610176, 0.16003519, 0.46564421, 0.32534567])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [8]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [9]:
#1
result_matrix = np.dot(B,A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [10]:
#2   2х1
np.dot(result_matrix,C)

array([[0.5202],
       [0.2846]])

In [11]:
#3 2x2
np.dot(result_matrix,D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [12]:
#1
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [13]:
vector = np.array(np.random.uniform(0,1,10))
vector

array([0.41389853, 0.95442182, 0.49569437, 0.63465198, 0.88864014,
       0.97291749, 0.0636825 , 0.90753582, 0.5295797 , 0.20243946])

In [14]:
#2 Змін не виявлено
vector.T

array([0.41389853, 0.95442182, 0.49569437, 0.63465198, 0.88864014,
       0.97291749, 0.0636825 , 0.90753582, 0.5295797 , 0.20243946])

In [15]:
#3
column_vector = np.expand_dims(vector,axis=1)
column_vector

array([[0.41389853],
       [0.95442182],
       [0.49569437],
       [0.63465198],
       [0.88864014],
       [0.97291749],
       [0.0636825 ],
       [0.90753582],
       [0.5295797 ],
       [0.20243946]])

In [16]:
#Вектор-рядок - завдяки використанню даною функції перетворився на вектор-стовпець. Добавилась нова вісь
vector.shape, column_vector.shape

((10,), (10, 1))

In [17]:
#відбулись заміни - замість стовпців - стали рядки. Але це двовимірна розмірність, оскільки візь лишається
column_vector.T

array([[0.41389853, 0.95442182, 0.49569437, 0.63465198, 0.88864014,
        0.97291749, 0.0636825 , 0.90753582, 0.5295797 , 0.20243946]])

In [21]:
vector.T.shape

(10,)